name: 'Jest coverage report'
description: 'Track your code coverage in each pull request.'
author: 'Artiom Tretjakovas <artiom.tretjakovas2@gmail.com>'
branding:
    icon: 'activity'
    color: 'gray-dark'
inputs:
    github_token:
        required: true
        description: 'A github access token'
    test_script:
        required: false
        description: 'A custom npm script to get coverage'
        default: npx jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
    threshold:
        required: false
        description: 'Coverage threshold. If total coverage is less than threshold, PR will be rejected'
    working_directory:
        required: false
        description: 'Custom working directory'
    diff_threshold:
        required: false
        description: 'Coverage difference threshold. If base and head branch total coverage decrease is more than threshold, PR will be rejected'
    new_files_threshold:
        required: false
        description: 'Coverage difference threshold for new files. If total coverage in new files is less than threshold, PR will be rejected'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.github_token }}
        - ${{ inputs.test_script }}
        - ${{ inputs.threshold }}
        - ${{ inputs.working_directory }}
        - ${{ inputs.diff_threshold }}
        - ${{ inputs.new_files_threshold }}
